### ISSUE TITLE
PDF issues

### ISSUE THREAD

**Issue by 3nids** [QGEP/docs#33]
* [ ] it's not possible to produce a PDF of the documentation (error 404) https://github.com/QGEP/QGEP/issues/239
* [ ] images outside chapter: If there are many images in a chapter, sometime they are on the next page in the next chapter. E.g. Chapter 1.1.3 Setup workstation - first two images belong to 1.1.2. https://github.com/QGEP/QGEP/issues/201
* [ ] Content list in QGEP.pdf is only 2 levels deep - can this be adapted to 3 or even 4 levels? https://github.com/QGEP/QGEP/issues/200

**Comment by sjib** [comment]
Remove sentece to create pdf

**Comment by sjib** [comment]
rst to pdf tool?

**Comment by sjib** [comment]
Could this help: https://cloudconvert.com/api/combine

**Comment by m-kuhn** [comment]
I don't think so, we don't have docx, jpg or pdf files.

**Comment by sjib** [comment]
Commented out link to pdf for the moment: https://qgep.github.io/docs/index.html

**Comment by sjib** [comment]
https://stackoverflow.com/questions/39534718/how-to-create-a-pdf-out-of-sphinx-documentation-tool/47720278#47720278
pip install rst2pdf
